### ISSUE TITLE
jukebox script crash with: TypeError: keyboard_setting() takes at most 3 arguments (5 given) 

### ISSUE THREAD

**Issue by wolkstein** [mark-me/Pi-Jukebox#7]
if i try to start pi-jukebox on my pi with 3,2" lcd i get this:

```
sudo python pi-jukebox.py 

Traceback (most recent call last):
  File "pi-jukebox.py", line 102, in <module>
    main()
  File "pi-jukebox.py", line 86, in main
    apply_settings()  # Check for first time settings and applies settings
  File "pi-jukebox.py", line 75, in apply_settings
    '/var/lib/mpd/music/')
TypeError: keyboard_setting() takes at most 3 arguments (5 given)
```

any ideas?
i have checked out the latest github master

**Comment by BerryVZ** [comment]
Have the same thing..
- Raspberry 2B
- Installed Jessie light (adafruit.com)
- Installed service avahi-daemon
- Installed git (version 2.1.4)
- Newest python version (2.7.9 [GCC 4.9.2] on Linux2)

When first screen appears 'No Music Directory', the OK button is nearly not pressable, only after many taps on the screen, the program reacts by crashing.

Error: 
TypeError: keyboard_setting() takes at most 3 arguments (5 given).

When altering the code by commenting out the last 2 arguments at keyboard_setting(), the program will not crash and show a search window. Here the onscreen keyboard reacts by printing random characters when typing. Must be because of the arguments commented out.

Touchscreen works ok when testing with 
sudo TSLIB_FBDEVICE=/dev/fb1 TSLIB_TSDEVICE=/dev/input/touchscreen ts_calibrate

Am a Newbee, please help..
